Feature/mutect filter (Adding command for mutect filter)
msk-access/postprocessing_variant_calls pull request #27
Opened 2024-01-30 16:53 UTC by rnaidu

Added code, documentation, and command(s) to post processing to call paired-sample filtering of input VCF files derived from MuTect software v.1.1.5

Input command:
"pv mutect paired-sample filter --help"

Input file(s) needed:

- input MuTect VCF file
- input MuTect txt standard file

2024-01-30 19:49 UTC, rnaidu commented
> My 2 cents
> 
> * [x]  we should use mutect1
> * [x]  command should follow same structure as vardict `pv mutect1 filter case-control`

good idea, changes have been made/committed!

2024-01-31 20:31 UTC, buehlere requested changes
Great work! A lot of this review is related to updating the filter script from what was there previously and improving overall code quality in the package.

2024-01-31 20:31 UTC, buehlere commented on postprocessing_variant_calls/mutect/mutect_process.py
> +from __future__ import division
we should remove this and make sure division still works.

2024-01-31 20:31 UTC, buehlere commented on postprocessing_variant_calls/mutect/mutect_class.py
> +        tvf = int(tad) / float(tdp)
We should also consider writing division error cases. For example, division by zero.

2024-01-31 20:31 UTC, buehlere commented on postprocessing_variant_calls/mutect/mutect_class.py
> +        nvf = int(nad) / float(ndp)
We should also consider writing division error cases. For example, division by zero.

2024-02-02 14:58 UTC, buehlere commented on test.txt
> +testing
we'll want to remove this. Could you also add a pytest like we do here: https://github.com/msk-access/postprocessing_variant_calls/blob/main/tests/test_maf.py? Just testing if the command `--help` works is fine. No need to use real data.

2024-02-05 16:28 UTC, buehlere approved these changes

2024-02-05 17:41 UTC, merged